<?php
// index.php - Music Player Main Interface with Song Management

// Include database functions
require_once 'database.php';

// Get all songs from the database
$songs = getSongs();

// If no songs in database, use a default placeholder to prevent errors
if (empty($songs)) {
    $songs = [
        [
            'id' => 0, // Use a placeholder ID for a default song
            'title' => "No Songs Available",
            'artist' => "Please Add a Song",
            'featuring' => "",
            'album' => "",
            'duration' => 0,
            'cover_image' => "https://placehold.co/500x500/3d3d62/ffffff?text=No+Songs",
            'lyrics' => "No songs in the database. Use the 'Add Song' button to upload your first track!",
            'audio_file' => ""
        ],
    ];
}

// Check if a message was passed (e.g., from upload.php)
$message = isset($_GET['message']) ? $_GET['message'] : '';

// Handle song deletion
if (isset($_GET['delete_id'])) {
    $delete_id = $_GET['delete_id'];
    if (deleteSong($delete_id)) {
        header("Location: index.php?message=Song deleted successfully!");
        exit();
    } else {
        $message = "Error deleting song.";
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ohm</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
    <!-- Modern Audio Visualizer Background -->
    <div class="audio-visualizer" id="audioVisualizer">
        <!-- Flowing Audio Waves -->
        <div class="wave-container">
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
            <div class="wave"></div>
        </div>
        
        <!-- Smooth Ambient Glow -->
        <div class="ambient-glow">
            <div class="glow-spot"></div>
            <div class="glow-spot"></div>
            <div class="glow-spot"></div>
        </div>
        
        <!-- Frequency Bars -->
        <div class="frequency-bars" id="frequencyBars">
            <!-- Bars will be dynamically generated by JavaScript -->
        </div>
    </div>

    <?php if (!empty($message)): ?>
        <div class="message"><?php echo htmlspecialchars($message); ?></div>
    <?php endif; ?>
    
    <div class="container">
        <div class="header">
            <h1 class="app-title">Ohm</h1>
            <button class="btn-add" id="toggleForm">
                <i class="fas fa-plus"></i> Add Song
            </button>
        </div>
        
        <div class="music-player">
            <div class="background-elements">
                <div class="circle circle-1"></div>
                <div class="circle circle-2"></div>
            </div>
            
            <div class="player-content">
                <div class="album-art" id="albumArt">
                    <img src="<?php echo !empty($songs[0]['cover_image']) ? $songs[0]['cover_image'] : 'https://placehold.co/500x500/3d3d62/ffffff?text=No+Image'; ?>" alt="Album Cover">
                </div>
                
                <div class="song-info">
                    <h1 class="song-title" id="songTitle"><?php echo htmlspecialchars($songs[0]['title']); ?></h1>
                    <p class="artist" id="artistName"><?php echo htmlspecialchars($songs[0]['artist']); ?></p>
                    <p class="featuring" id="featuringArtists"><?php echo htmlspecialchars($songs[0]['featuring']); ?></p>
                    <p class="album" id="albumName"><?php echo htmlspecialchars($songs[0]['album']); ?></p>
                    
                    <div class="lyrics" id="lyrics">
                        <p><?php echo htmlspecialchars($songs[0]['lyrics']); ?></p>
                    </div>
                    
                    <div class="progress-container" id="progressContainer">
                        <div class="progress" id="progress"></div>
                    </div>
                    
                    <div class="time-display">
                        <span id="currentTime">00:00</span>
                        <span id="totalTime"><?php echo !empty($songs[0]['duration']) ? gmdate("i:s", $songs[0]['duration']) : '00:00'; ?></span>
                    </div>
                    
                    <div class="controls">
                        <button class="btn" id="shuffleBtn">
                            <i class="fas fa-random"></i>
                        </button>
                        <button class="btn" id="prevBtn">
                            <i class="fas fa-step-backward"></i>
                        </button>
                        <button class="btn btn-play" id="playBtn">
                            <i class="fas fa-play" id="playIcon"></i>
                        </button>
                        <button class="btn" id="nextBtn">
                            <i class="fas fa-step-forward"></i>
                        </button>
                        <button class="btn" id="repeatBtn">
                            <i class="fas fa-redo"></i>
                        </button>
                    </div>
                    
                    <div class="volume-control">
                        <i class="fas fa-volume-down"></i>
                        <input type="range" class="volume-slider" id="volumeSlider" min="0" max="100" value="80">
                        <i class="fas fa-volume-up"></i>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="playlist-section">
            <h3>Playlist</h3>
            <div class="playlist" id="playlist">
                <?php foreach ($songs as $index => $song): ?>
                <div class="playlist-item <?php echo $index === 0 ? 'active' : ''; ?>" data-index="<?php echo $index; ?>">
                    <img src="<?php echo htmlspecialchars($song['cover_image']); ?>" alt="<?php echo htmlspecialchars($song['title']); ?>">
                    <div class="playlist-info">
                        <h4><?php echo htmlspecialchars($song['title']); ?></h4>
                        <p><?php echo htmlspecialchars($song['artist']); ?> <?php echo htmlspecialchars($song['featuring']); ?></p>
                    </div>
                    <div class="playlist-duration"><?php echo !empty($song['duration']) ? gmdate("i:s", $song['duration']) : '00:00'; ?></div>
                    <?php if ($song['id'] > 0): ?>
                    <div class="playlist-actions">
                        <button class="delete-btn" onclick="deleteSong(<?php echo $song['id']; ?>)" title="Delete Song">
                            <i class="fas fa-trash"></i>
                        </button>
                    </div>
                    <?php endif; ?>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        
        <div class="upload-form" id="uploadForm">
            <h2>Add New Song</h2>
            
            <form action="upload.php" method="post" enctype="multipart/form-data" id="songForm">
                <div class="form-grid">
                    <div class="form-group">
                        <label for="songTitle">Song Title *</label>
                        <input type="text" id="songTitle" name="title" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="artistName">Artist *</label>
                        <input type="text" id="artistName" name="artist" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="featuring">Featuring (optional)</label>
                        <input type="text" id="featuring" name="featuring" placeholder="Feat. Artist1, Artist2">
                    </div>
                    
                    <div class="form-group">
                        <label for="album">Album *</label>
                        <input type="text" id="album" name="album" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="durationInput">Duration (MM:SS) *</label>
                        <input type="text" id="durationInput" placeholder="03:45" pattern="[0-9]{1,2}:[0-5][0-9]" title="Please enter time in MM:SS format" required>
                        <input type="hidden" id="duration" name="duration">
                    </div>
                    
                    <div class="form-group">
                        <label for="coverImage">Cover Image</label>
                        <input type="file" id="coverImage" name="cover_image" accept="image/*">
                    </div>
                    
                    <div class="form-group">
                        <label for="lyrics">Lyrics Excerpt *</label>
                        <textarea id="lyrics" name="lyrics" required></textarea>
                    </div>
                    
                    <div class="form-group">
                        <label for="audioFile">Audio File *</label>
                        <input type="file" id="audioFile" name="audio_file" accept="audio/*" required>
                    </div>
                </div>
                
                <button type="submit" class="submit-btn">Upload Song</button>
            </form>
        </div>
    </div>
    
    <script>
        // Pass PHP songs data to JavaScript
        const songs = <?php echo json_encode($songs, JSON_UNESCAPED_SLASHES); ?>;
        
        // Delete song function
        function deleteSong(songId) {
            if (confirm('Are you sure you want to delete this song?')) {
                window.location.href = 'index.php?delete_id=' + songId;
            }
        }
    </script>
    <script src="script.js"></script>
</body>
</html>