<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PHP Music Player</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="style.css">
    <script src="script.js"></script>
</head>
<body>
    <div class="container">
        <div class="music-player">
            <div class="background-elements">
                <div class="circle circle-1"></div>
                <div class="circle circle-2"></div>
            </div>
            
            <div class="header">
                <h1>Now Playing</h1>
                <i class="fas fa-heart"></i>
            </div>
            
            <div class="album-art" id="albumArt">
                <img src="https://images.unsplash.com/photo-1470225620780-dba8ba36b745?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80" alt="Album Cover">
            </div>
            
            <div class="song-info">
                <h1 class="song-title" id="songTitle">Heroes & Villains</h1>
                <p class="artist" id="artistName">Métro Boomin</p>
                <p class="featuring" id="featuringArtists">(Feat. Don Toliver & Future)</p>
                <p class="album" id="albumName">Too Many Nights</p>
            </div>
            
            <div class="progress-container" id="progressContainer">
                <div class="progress" id="progress"></div>
            </div>
            
            <div class="time-display">
                <span id="currentTime">01:09</span>
                <span id="totalTime">03:19</span>
            </div>
            
            <div class="lyrics" id="lyrics">
                <p>I guess you got what you wanted</p>
            </div>
            
            <div class="controls">
                <button class="btn" id="shuffleBtn">
                    <i class="fas fa-random"></i>
                </button>
                <button class="btn" id="prevBtn">
                    <i class="fas fa-step-backward"></i>
                </button>
                <button class="btn btn-play" id="playBtn">
                    <i class="fas fa-play" id="playIcon"></i>
                </button>
                <button class="btn" id="nextBtn">
                    <i class="fas fa-step-forward"></i>
                </button>
                <button class="btn" id="repeatBtn">
                    <i class="fas fa-redo"></i>
                </button>
            </div>
            
            <div class="volume-control">
                <i class="fas fa-volume-down"></i>
                <input type="range" class="volume-slider" id="volumeSlider" min="0" max="100" value="80">
                <i class="fas fa-volume-up"></i>
            </div>
            
            <div class="playlist" id="playlist">
                <!-- Playlist will be generated by JavaScript -->
            </div>
        </div>

        <div class="songs-management">
            <h2>Manage Your Music</h2>
            
            <div class="upload-form">
                <h3>Add New Song</h3>
                <form action="upload.php" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label for="songTitle">Song Title</label>
                        <input type="text" id="songTitle" name="title" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="artistName">Artist</label>
                        <input type="text" id="artistName" name="artist" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="featuring">Featuring (optional)</label>
                        <input type="text" id="featuring" name="featuring" placeholder="Feat. Artist1, Artist2">
                    </div>
                    
                    <div class="form-group">
                        <label for="album">Album</label>
                        <input type="text" id="album" name="album" required>
                    </div>
                    
                    <div class="form-group">
                        <label for="lyrics">Lyrics Excerpt</label>
                        <textarea id="lyrics" name="lyrics" required></textarea>
                    </div>
                    
                    <div class="form-group">
                        <label for="coverImage">Cover Image</label>
                        <input type="file" id="coverImage" name="cover_image" accept="image/*">
                    </div>
                    
                    <div class="form-group">
                        <label for="audioFile">Audio File</label>
                        <input type="file" id="audioFile" name="audio_file" accept="audio/*" required>
                    </div>
                    
                    <button type="submit" class="submit-btn">Upload Song</button>
                </form>
            </div>
            
            <div class="songs-list">
                <h3>Your Songs</h3>
                <div class="song-item">
                    <div class="song-details">
                        <h4>Heroes & Villains</h4>
                        <p>Métro Boomin • Too Many Nights</p>
                    </div>
                    <div class="song-actions">
                        <button class="action-btn"><i class="fas fa-play"></i></button>
                        <button class="action-btn"><i class="fas fa-edit"></i></button>
                        <button class="action-btn"><i class="fas fa-trash"></i></button>
                    </div>
                </div>
                
                <div class="song-item">
                    <div class="song-details">
                        <h4>Blinding Lights</h4>
                        <p>The Weeknd • After Hours</p>
                    </div>
                    <div class="song-actions">
                        <button class="action-btn"><i class="fas fa-play"></i></button>
                        <button class="action-btn"><i class="fas fa-edit"></i></button>
                        <button class="action-btn"><i class="fas fa-trash"></i></button>
                    </div>
                </div>
                
                <div class="song-item">
                    <div class="song-details">
                        <h4>Save Your Tears</h4>
                        <p>The Weeknd • After Hours</p>
                    </div>
                    <div class="song-actions">
                        <button class="action-btn"><i class="fas fa-play"></i></button>
                        <button class="action-btn"><i class="fas fa-edit"></i></button>
                        <button class="action-btn"><i class="fas fa-trash"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>